try {
	let a = 42;
} catch (error) {
	let b = error;
}
throw new Error("this is an error");
